### PR TITLE
Udw parser

### PR DESCRIPTION
**Pull request by stobajas**
Hello,
We are contractors for CBC. We are working on a SMPTE 2110 decoder and we improved your dissector by adding User Data Words decoder and timecode parsing.
Closed Captioned data parsing is still in work in progress.
Feel free to comment.
Thanks for your work
Best regards,
Sandra

### CODE REVIEW

**Comment by NEOAdvancedTechnology** [comment]
Thanks for the pull request!

I’ve checked out the pull request locally, and on Wireshark Version 2.4.4 (v2.4.4-0-g90a7be1) on Mac OS X, I’m getting this error message on dissector load:

Lua: Error during loading:
[string "/Applications/Wireshark.app/Contents/PlugIns/..."]:67: bad argument #3 to 'string' (Display must be either base.ASCII or base.UNICODE)

-Thomas

**Comment by stobajas** [comment]
Hi, 
I've added some parsing of the CC data packets and also CDP section. I've also fixed and check the plugin for Wireshark 2.4.6 (the handling of the string types was different).
I am not sure if the parsing is going well, since I don't think I have the correct network captures of CCData.
Do you have any captures in order to test and to keep going working on the parsing ?

Regards,
Sandra

**Comment by NEOAdvancedTechnology** [comment]
Here is a ST 2110-40 ANC capture with 30 seconds of Closed Captions (708):

https://github.com/FOXNEOAdvancedTechnology/ST2110_pcap_zoo/blob/master/ST2110-40-Closed_Captions.cap

-Thomas

**Comment by NEOAdvancedTechnology** [comment]
Your pull request seems to work now on Wireshark (v2.4.4-0-g90a7be1) for Mac OS X.  The only odd thing is that it says "(null)" before the "User Data Words" dissection, but I think it adds enough value to merge your pull at this time.

Thanks!

-Thomas

**Comment by stobajas** [comment]
Thank you for the merge. I will take a look to your capture. I'm aware of the "null" field before the "User Data Words", but I didn't find a way to fix this. Also i didn't find the solution to name the new tabs in Lua.
Sandra

**Pull request merged**
